### ISSUE TITLE
Support Adwords API v201502

### ISSUE THREAD

**Issue by alexhayes** [alexhayes/django-google-adwords#1]
As indicated by [Aasif Saifuddin](https://bitbucket.org/auvipy) on the old bitbucket repo:

> v201409 is depricated from 5 March 2015 and will sunset on 14 July 2015. so please upgrade to latest API and googleads versions too.

**Comment by auvipy** [comment]
how much existing model fields need to be changed?

**Comment by alexhayes** [comment]
Not that many, but there will be some - details of what's changed is available at https://developers.google.com/adwords/api/docs/guides/migration/v201502

The main changes that we have to implement are for the Reporting/Reports services.

**Comment by auvipy** [comment]
thats good to hear!!

**Comment by alexhayes** [comment]
Fixed in 2177d9dfae2c28d8850d268757094b66d5362835

Note that we upgraded to [v201506](https://developers.google.com/adwords/api/docs/guides/migration/v201506) as just today they announced the sunset dates on [v201502](https://developers.google.com/adwords/api/docs/guides/migration/v201502).

Note we didn't need to break any backwards compatibility - only the calling API changed, not the fields contained within the reports.

You can updated your installation with: `pip install -U django-google-adwords`

**Comment by auvipy** [comment]
thats great!!!
