### ISSUE TITLE
auto_now, auto_now_add, and default are mutually exclusive

### ISSUE THREAD

**Issue by alexhayes** [alexhayes/django-google-adwords#2]
As reported by [Aasif Saifuddin](https://bitbucket.org/auvipy) on the old bitbucket repo:

> python manage.py migrate SystemCheckError: System check identified some issues:
> ERRORS: adwords.Account.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present. adwords.Ad.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present. adwords.AdGroup.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present. adwords.Alert.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present. adwords.Campaign.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present. adwords.DailyAccountMetrics.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present. adwords.DailyAdGroupMetrics.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present. adwords.DailyAdMetrics.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present. adwords.DailyCampaignMetrics.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present.

**Comment by auvipy** [comment]
i solved this issue by choosing only auto_now_add=True and removing auto_now as in django 1.8 both are mututally intelligible

**Comment by auvipy** [comment]
Only one of these options may be present.

**Comment by auvipy** [comment]
should i sent any pr? what are your thoughts?

**Comment by alexhayes** [comment]
Yes certainly.

**Comment by auvipy** [comment]
then I will only keep the auto_now_add and send the PR

**Comment by yangchandle** [comment]
how solved this problem

**Comment by emmadinortey** [comment]
I solved this by making models.DateField(default='01-01-01')
